version: "3.9"
services:
  web:
    container_name: swap-me-web
    image: thongdh3401/swap-me-web:${RELEASE}
    ports:
      - "5173:80"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - services
  services:
    container_name: swap-me-services
    image: thongdh3401/swap-me-services:${RELEASE}
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
        - mysqlDB
        - keycloak
  identity-access-management:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.4
    command: [ "start"]
    environment:
      # Database Configuration
      KC_DB: "mysql"
      KC_DB_URL_HOST: "mysqlDB"
      KC_DB_USERNAME: ${KC_DB_USERNAME
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      # Proxy Configuration
      KC_PROXY_HEADERS: "xforwarded"
      KC_HTTP_RELATIVE_PATH: ${KC_HTTP_RELATIVE_PATH}
      #TLS Configuration
      KC_HTTPS_CERTIFICATE_FILE: "/keycloak/tls/fullchain.pem"
      KC_HTTPS_CERTIFICATE_KEY_FILE: "/keycloak/tls/private.pem"
      #Hostname Configuration
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT_HTTPS: 'true'
      #Admin Credentials
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./fullchain.pem:/keycloak/tls/fullchain.pem
      - ./private.pem:/keycloak/tls/private.pem
      - ./swapme-theme:/opt/keycloak/themes/swapme
    ports:
      - "8443:8443"
    depends_on:
      - mysqlDB
  mysqlDB:
    container_name: mysqlDB
    image: mysql:8.0
    environment:
      TZ: Asia/Ho_Chi_Minh
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "3306:3306"