name: PR Review

on:
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
    frontend-lint:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
  
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
  
      - name: Run ESLint
        run: npm run lint
        working-directory: frontend

    backend-lint:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Use Node.js 20
          uses: actions/setup-node@v3
          with:
            node-version: 14
            cache: 'npm'
  
        - name: Install dependencies
          run: npm ci
          working-directory: backend
    
        - name: Run ESLint
          run: npm run lint
          working-directory: backend
