name: PR Review

on:
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm -v
      - run: cd frontend && npm ci
      - run: cd frontend && npm run lint
      - run: cd backend && npm ci
      - run: cd backend && npm run lint
